# Generated by Django 2.1.15 on 2022-04-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'TERRACED'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('DETACHED', 'DETACHED'), ('PARKING SPACE', 'PARKING SPACE'), ('SITE', 'SITE'), ('APPARTMENT', 'APPARTMENT'), ('BUNGALOW', 'BUNGALOW')], default='BUNGALOW', max_length=20),
        ),
    ]
