# Generated by Django 2.1.15 on 2022-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220407_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('3', '3'), ('8', '8'), ('1', '1'), ('6', '6'), ('9', '9'), ('10+', '10+'), ('7', '7'), ('5', '5'), ('4', '4'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Armagh', 'Armagh'), ('Derry', 'Derry'), ('Down', 'Down'), ('Westmeath', 'Westmeath'), ('Antrim', 'Antrim'), ('Kerry', 'Kerry'), ('Offaly', 'Offaly'), ('Dublin', 'Dublin'), ('Limerick', 'Limerick'), ('Meath', 'Meath'), ('Galway', 'Galway'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Tipperary', 'Tipperary'), ('Wicklow', 'Wicklow'), ('Carlow', 'Carlow'), ('Cork', 'Cork'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Waterford', 'Waterford'), ('Wexford', 'Wexford'), ('Fermanagh', 'Fermanagh'), ('Roscommon', 'Roscommon'), ('Monaghan', 'Monaghan'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Leitrim', 'Leitrim'), ('Tyrone', 'Tyrone'), ('Donegal', 'Donegal'), ('Longford', 'Longford'), ('Sligo', 'Sligo')], default='Carlow', max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='53.423596', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR LEASE', 'FOR LEASE'), ('FOR SALE', 'FOR SALE')], default='FOR SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='-7.934211', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SEMI-DETACHED', 'SEMI-DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('SITE', 'SITE'), ('DETACHED', 'DETACHED'), ('APPARTMENT', 'APPARTMENT'), ('PARKING SPACE', 'PARKING SPACE'), ('TERRACED', 'TERRACED')], default='BUNGALOW', max_length=20),
        ),
    ]
