# Generated by Django 2.1.15 on 2022-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20220407_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('9', '9'), ('5', '5'), ('1', '1'), ('6', '6'), ('7', '7'), ('8', '8'), ('3', '3'), ('10+', '10+'), ('4', '4'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Roscommon', 'Roscommon'), ('Limerick', 'Limerick'), ('Antrim', 'Antrim'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Monaghan', 'Monaghan'), ('Wexford', 'Wexford'), ('Armagh', 'Armagh'), ('Clare', 'Clare'), ('Offaly', 'Offaly'), ('Sligo', 'Sligo'), ('Westmeath', 'Westmeath'), ('Carlow', 'Carlow'), ('Kerry', 'Kerry'), ('Wicklow', 'Wicklow'), ('Longford', 'Longford'), ('Mayo', 'Mayo'), ('Cavan', 'Cavan'), ('Galway', 'Galway'), ('Leitrim', 'Leitrim'), ('Laois', 'Laois'), ('Meath', 'Meath'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Donegal', 'Donegal'), ('Fermanagh', 'Fermanagh'), ('Louth', 'Louth'), ('Tipperary', 'Tipperary')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'TERRACED'), ('BUNGALOW', 'BUNGALOW'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('APPARTMENT', 'APPARTMENT'), ('SITE', 'SITE'), ('DETACHED', 'DETACHED'), ('PARKING SPACE', 'PARKING SPACE')], default='BUNGALOW', max_length=20),
        ),
    ]
