# Generated by Django 2.1.15 on 2022-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20220408_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('A3', 'A3'), ('B2', 'B2'), ('B1', 'B1'), ('C1', 'C1'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('G', 'G'), ('B3', 'B3'), ('E1', 'E1'), ('E2', 'E2'), ('C2', 'C2'), ('F', 'F'), ('A1', 'A1'), ('A2', 'A2')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('7', '7'), ('1', '1'), ('10+', '10+'), ('2', '2'), ('8', '8'), ('5', '5'), ('4', '4'), ('6', '6'), ('9', '9'), ('3', '3')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Mayo', 'Mayo'), ('Cork', 'Cork'), ('Kerry', 'Kerry'), ('Kilkenny', 'Kilkenny'), ('Westmeath', 'Westmeath'), ('Clare', 'Clare'), ('Armagh', 'Armagh'), ('Cavan', 'Cavan'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Laois', 'Laois'), ('Sligo', 'Sligo'), ('Wicklow', 'Wicklow'), ('Derry', 'Derry'), ('Waterford', 'Waterford'), ('Wexford', 'Wexford'), ('Leitrim', 'Leitrim'), ('Offaly', 'Offaly'), ('Carlow', 'Carlow'), ('Louth', 'Louth'), ('Monaghan', 'Monaghan'), ('Kildare', 'Kildare'), ('Down', 'Down'), ('Donegal', 'Donegal'), ('Meath', 'Meath'), ('Roscommon', 'Roscommon'), ('Antrim', 'Antrim'), ('Tyrone', 'Tyrone'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Galway', 'Galway'), ('Tipperary', 'Tipperary')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APPARTMENT', 'APPARTMENT'), ('PARKING SPACE', 'PARKING SPACE'), ('TERRACED', 'TERRACED'), ('DETACHED', 'DETACHED'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('SITE', 'SITE'), ('BUNGALOW', 'BUNGALOW')], default='BUNGALOW', max_length=20),
        ),
    ]
