# Generated by Django 2.1.15 on 2022-04-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20220408_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('10+', '10+'), ('5', '5'), ('3', '3'), ('4', '4'), ('8', '8'), ('1', '1'), ('7', '7'), ('9', '9'), ('6', '6'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('B1', 'B1'), ('C3', 'C3'), ('D2', 'D2'), ('E2', 'E2'), ('B2', 'B2'), ('A2', 'A2'), ('G', 'G'), ('D1', 'D1'), ('B3', 'B3'), ('F', 'F'), ('A1', 'A1'), ('C2', 'C2'), ('C1', 'C1'), ('A3', 'A3'), ('E1', 'E1')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Cavan', 'Cavan'), ('Kildare', 'Kildare'), ('Roscommon', 'Roscommon'), ('Louth', 'Louth'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Wicklow', 'Wicklow'), ('Meath', 'Meath'), ('Limerick', 'Limerick'), ('Waterford', 'Waterford'), ('Cork', 'Cork'), ('Kilkenny', 'Kilkenny'), ('Clare', 'Clare'), ('Down', 'Down'), ('Mayo', 'Mayo'), ('Derry', 'Derry'), ('Longford', 'Longford'), ('Tyrone', 'Tyrone'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Kerry', 'Kerry'), ('Laois', 'Laois'), ('Tipperary', 'Tipperary'), ('Antrim', 'Antrim'), ('Donegal', 'Donegal'), ('Wexford', 'Wexford'), ('Leitrim', 'Leitrim'), ('Sligo', 'Sligo'), ('Westmeath', 'Westmeath'), ('Galway', 'Galway')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APPARTMENT', 'APPARTMENT'), ('PARKING SPACE', 'PARKING SPACE'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('DETACHED', 'DETACHED'), ('SITE', 'SITE'), ('BUNGALOW', 'BUNGALOW'), ('TERRACED', 'TERRACED')], default='BUNGALOW', max_length=20),
        ),
    ]
