# Generated by Django 2.1.15 on 2022-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20220408_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('9', '9'), ('6', '6'), ('8', '8'), ('4', '4'), ('2', '2'), ('7', '7'), ('10+', '10+'), ('3', '3'), ('5', '5')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('E1', 'E1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2'), ('B3', 'B3'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('E2', 'E2'), ('B1', 'B1'), ('C1', 'C1'), ('C2', 'C2'), ('F', 'F'), ('G', 'G'), ('A3', 'A3')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Cavan', 'Cavan'), ('Carlow', 'Carlow'), ('Derry', 'Derry'), ('Fermanagh', 'Fermanagh'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Dublin', 'Dublin'), ('Louth', 'Louth'), ('Cork', 'Cork'), ('Kerry', 'Kerry'), ('Longford', 'Longford'), ('Galway', 'Galway'), ('Laois', 'Laois'), ('Offaly', 'Offaly'), ('Antrim', 'Antrim'), ('Down', 'Down'), ('Tyrone', 'Tyrone'), ('Tipperary', 'Tipperary'), ('Limerick', 'Limerick'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Westmeath', 'Westmeath'), ('Clare', 'Clare'), ('Leitrim', 'Leitrim'), ('Armagh', 'Armagh'), ('Kilkenny', 'Kilkenny'), ('Monaghan', 'Monaghan'), ('Waterford', 'Waterford'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow'), ('Kildare', 'Kildare'), ('Donegal', 'Donegal')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='description', max_length=600),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR SALE', 'FOR SALE'), ('FOR LEASE', 'FOR LEASE')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'BUNGALOW'), ('PARKING SPACE', 'PARKING SPACE'), ('SITE', 'SITE'), ('TERRACED', 'TERRACED'), ('DETACHED', 'DETACHED'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('APPARTMENT', 'APPARTMENT')], default='BUNGALOW', max_length=20),
        ),
    ]
