# Generated by Django 2.0.2 on 2022-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20220412_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('1', '1'), ('8', '8'), ('10+', '10+'), ('7', '7'), ('4', '4'), ('3', '3'), ('9', '9'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('F', 'F'), ('B1', 'B1'), ('D2', 'D2'), ('B2', 'B2'), ('A1', 'A1'), ('B3', 'B3'), ('E1', 'E1'), ('A2', 'A2'), ('E2', 'E2'), ('D1', 'D1'), ('A3', 'A3'), ('C3', 'C3'), ('G', 'G'), ('C2', 'C2'), ('C1', 'C1')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Galway', 'Galway'), ('Louth', 'Louth'), ('Carlow', 'Carlow'), ('Armagh', 'Armagh'), ('Donegal', 'Donegal'), ('Leitrim', 'Leitrim'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Fermanagh', 'Fermanagh'), ('Westmeath', 'Westmeath'), ('Dublin', 'Dublin'), ('Sligo', 'Sligo'), ('Laois', 'Laois'), ('Tipperary', 'Tipperary'), ('Longford', 'Longford'), ('Tyrone', 'Tyrone'), ('Cavan', 'Cavan'), ('Meath', 'Meath'), ('Roscommon', 'Roscommon'), ('Kerry', 'Kerry'), ('Wicklow', 'Wicklow'), ('Derry', 'Derry'), ('Waterford', 'Waterford'), ('Down', 'Down'), ('Kildare', 'Kildare'), ('Mayo', 'Mayo'), ('Clare', 'Clare'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Limerick', 'Limerick'), ('Antrim', 'Antrim'), ('Cork', 'Cork')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('BUNGALOW', 'BUNGALOW'), ('TERRACED', 'TERRACED'), ('SITE', 'SITE'), ('PARKING SPACE', 'PARKING SPACE'), ('DETACHED', 'DETACHED'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('APPARTMENT', 'APPARTMENT')], default='BUNGALOW', max_length=20),
        ),
    ]
