# Generated by Django 2.0.2 on 2022-04-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20220412_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('8', '8'), ('9', '9'), ('4', '4'), ('1', '1'), ('7', '7'), ('10+', '10+'), ('3', '3'), ('6', '6')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('D2', 'D2'), ('A3', 'A3'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('E2', 'E2'), ('F', 'F'), ('B1', 'B1'), ('G', 'G'), ('A1', 'A1'), ('C1', 'C1'), ('C3', 'C3'), ('D1', 'D1'), ('B3', 'B3'), ('E1', 'E1')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Down', 'Down'), ('Armagh', 'Armagh'), ('Leitrim', 'Leitrim'), ('Sligo', 'Sligo'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow'), ('Waterford', 'Waterford'), ('Antrim', 'Antrim'), ('Donegal', 'Donegal'), ('Carlow', 'Carlow'), ('Laois', 'Laois'), ('Cavan', 'Cavan'), ('Tipperary', 'Tipperary'), ('Cork', 'Cork'), ('Kildare', 'Kildare'), ('Meath', 'Meath'), ('Limerick', 'Limerick'), ('Louth', 'Louth'), ('Longford', 'Longford'), ('Galway', 'Galway'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Fermanagh', 'Fermanagh'), ('Mayo', 'Mayo'), ('Clare', 'Clare'), ('Dublin', 'Dublin'), ('Kerry', 'Kerry'), ('Tyrone', 'Tyrone'), ('Westmeath', 'Westmeath'), ('Derry', 'Derry'), ('Kilkenny', 'Kilkenny')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='description', max_length=600),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR SALE', 'FOR SALE'), ('FOR LEASE', 'FOR LEASE')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SITE', 'SITE'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('DETACHED', 'DETACHED'), ('PARKING SPACE', 'PARKING SPACE'), ('APPARTMENT', 'APPARTMENT'), ('TERRACED', 'TERRACED')], default='BUNGALOW', max_length=20),
        ),
    ]
