# Generated by Django 2.0.2 on 2022-04-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20220415_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('10+', '10+'), ('2', '2'), ('4', '4'), ('6', '6'), ('5', '5'), ('7', '7'), ('1', '1'), ('9', '9'), ('3', '3'), ('8', '8')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('F', 'F'), ('E2', 'E2'), ('B2', 'B2'), ('A2', 'A2'), ('B1', 'B1'), ('A3', 'A3'), ('C1', 'C1'), ('C2', 'C2'), ('A1', 'A1'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('G', 'G'), ('B3', 'B3'), ('C3', 'C3')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Wicklow', 'Wicklow'), ('Carlow', 'Carlow'), ('Cork', 'Cork'), ('Cavan', 'Cavan'), ('Monaghan', 'Monaghan'), ('Tipperary', 'Tipperary'), ('Laois', 'Laois'), ('Limerick', 'Limerick'), ('Armagh', 'Armagh'), ('Roscommon', 'Roscommon'), ('Galway', 'Galway'), ('Louth', 'Louth'), ('Sligo', 'Sligo'), ('Wexford', 'Wexford'), ('Leitrim', 'Leitrim'), ('Clare', 'Clare'), ('Donegal', 'Donegal'), ('Mayo', 'Mayo'), ('Kildare', 'Kildare'), ('Longford', 'Longford'), ('Tyrone', 'Tyrone'), ('Fermanagh', 'Fermanagh'), ('Westmeath', 'Westmeath'), ('Waterford', 'Waterford'), ('Antrim', 'Antrim'), ('Kilkenny', 'Kilkenny'), ('Derry', 'Derry'), ('Meath', 'Meath'), ('Offaly', 'Offaly'), ('Kerry', 'Kerry'), ('Down', 'Down'), ('Dublin', 'Dublin')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SEMI-DETACHED', 'SEMI-DETACHED'), ('TERRACED', 'TERRACED'), ('DETACHED', 'DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('APPARTMENT', 'APPARTMENT'), ('PARKING SPACE', 'PARKING SPACE'), ('SITE', 'SITE')], default='BUNGALOW', max_length=20),
        ),
    ]
