# Generated by Django 2.1 on 2022-04-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20220415_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('9', '9'), ('4', '4'), ('1', '1'), ('5', '5'), ('2', '2'), ('6', '6'), ('3', '3'), ('8', '8'), ('10+', '10+'), ('7', '7')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('B3', 'B3'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('A3', 'A3'), ('D2', 'D2'), ('A2', 'A2'), ('E2', 'E2'), ('C1', 'C1'), ('F', 'F'), ('G', 'G'), ('E1', 'E1'), ('B2', 'B2')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Cavan', 'Cavan'), ('Carlow', 'Carlow'), ('Donegal', 'Donegal'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Limerick', 'Limerick'), ('Laois', 'Laois'), ('Dublin', 'Dublin'), ('Louth', 'Louth'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Antrim', 'Antrim'), ('Down', 'Down'), ('Longford', 'Longford'), ('Cork', 'Cork'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Waterford', 'Waterford'), ('Derry', 'Derry'), ('Leitrim', 'Leitrim'), ('Wexford', 'Wexford'), ('Kilkenny', 'Kilkenny'), ('Mayo', 'Mayo'), ('Offaly', 'Offaly'), ('Clare', 'Clare'), ('Tyrone', 'Tyrone'), ('Wicklow', 'Wicklow'), ('Westmeath', 'Westmeath'), ('Armagh', 'Armagh'), ('Kildare', 'Kildare')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR LEASE', 'FOR LEASE'), ('FOR SALE', 'FOR SALE')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SITE', 'SITE'), ('APPARTMENT', 'APPARTMENT'), ('PARKING SPACE', 'PARKING SPACE'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('DETACHED', 'DETACHED'), ('TERRACED', 'TERRACED')], default='BUNGALOW', max_length=20),
        ),
    ]
