# Generated by Django 2.1 on 2022-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20220418_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user_email',
            field=models.EmailField(default='ravina.mestry@gmail.com', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='ber_rating',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('E2', 'E2'), ('F', 'F'), ('G', 'G')], default='A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Carlow', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='53.28265136571093', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='-6.3206235609398', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'TERRACED'), ('PARKING SPACE', 'PARKING SPACE'), ('APPARTMENT', 'APPARTMENT'), ('SITE', 'SITE'), ('SEMI-DETACHED', 'SEMI-DETACHED'), ('DETACHED', 'DETACHED'), ('BUNGALOW', 'BUNGALOW')], default='BUNGALOW', max_length=20),
        ),
    ]
