# Generated by Django 2.1 on 2022-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20220419_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR SALE', 'FOR SALE'), ('FOR LEASE', 'FOR LEASE')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('TERRACED', 'TERRACED'), ('SITE', 'SITE'), ('PARKING SPACE', 'PARKING SPACE'), ('APPARTMENT', 'APPARTMENT'), ('DETACHED', 'DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('SEMI-DETACHED', 'SEMI-DETACHED')], default='BUNGALOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='property',
            name='user_email',
            field=models.CharField(max_length=64),
        ),
    ]
