# Generated by Django 2.1 on 2022-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20220419_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user_email',
        ),
        migrations.AddField(
            model_name='property',
            name='agent_email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('FOR LEASE', 'FOR LEASE'), ('FOR SALE', 'FOR SALE')], default='FOR SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SEMI-DETACHED', 'SEMI-DETACHED'), ('BUNGALOW', 'BUNGALOW'), ('DETACHED', 'DETACHED'), ('SITE', 'SITE'), ('PARKING SPACE', 'PARKING SPACE'), ('APPARTMENT', 'APPARTMENT'), ('TERRACED', 'TERRACED')], default='BUNGALOW', max_length=20),
        ),
    ]
